INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (0, 1, N'Wanna Be Startin Somethin', 2);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (1, 1, N'Baby Be Mine', 4);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (2, 1, N'The Girl Is Mine', 3);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (3, 1, N'Thriller', 5);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (4, 1, N'Beat It', 5);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (5, 1, N'Billie Jean', 4);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (6, 1, N'Human Nature', 3);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (7, 1, N'P.Y.T. (Pretty Young Thing)', 2);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (8, 1, N'The Lady in My Life', 2);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (9, 2, N'Imagine', 3);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (10, 2, N'How?', 3);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (11, 0, N'Takeover', 3);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (12, 0, N'The Ruler''s Back', 2);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (13, 2, N'Oh Yoko!', 2);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (14, 3, N'Hot n Cold', 2);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (15, 0, N'Izzo', 4);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (16, 0, N'Never Change', 3);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (17, 0, N'Girls, Girls, Girls', 5);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (18, 3, N'Roar', 5);
INSERT INTO MusicApplication.musicapplication_schema.Song (sid, aid, name, length) VALUES (19, 5, N'SCM!!', 7);